# name: Build on dispatch
# on: [push, repository_dispatch]
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.event.action == 'start_build'
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.x
#       - name: Build Client
#         run: |
#           npm install
#           npm run build:prod
#       - name: Push newly built client to Github
#         run: |
#           git config --global user.name '${GITHUB_ACTOR}'
#           git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
#           git add -u
#           git commit -m "Rebuild client" || echo "No changes to commit"
#           git push origin ${GITHUB_REF##*/} || echo "No changes to commit"
#       - name: Dispatch response to server repo build request
#         run: |
#           curl -X POST https://api.github.com/repos/dean-shaff/planet-tracker/dispatches \
#           -H 'Accept: application/vnd.github.everest-preview+json' \
#           -u ${{ secrets.ACCESS_TOKEN }} \
#           --data '{"event_type": "build_completed", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
