name: Trigger server rebuild
on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch  server repo build request
        run: |
          curl -X POST https://api.github.com/repos/dean-shaff/planet-tracker/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "build", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
