name: Build Production App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build Client
      run: |
        npm install
        npm run build:prod
    - name: Push newly built client to Github
      run: |
        git config --global user.name '${GITHUB_ACTOR}'
        git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        git add -u
        git commit -m "Rebuild client" || echo "No changes to commit"
        git push origin ${GITHUB_REF##*/} || echo "No changes to commit"
